name: github_apk_updater
description: >
  Auto-update your Flutter Android app via GitHub Releases.
  Zero cost, zero third-party services, zero server needed.
  Just push to GitHub — users get update dialog automatically.
version: 1.0.9
homepage: https://github.com/Mans610/github_apk_updater
repository: https://github.com/Mans610/github_apk_updater

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android: